### ISSUE TITLE
This Font is Great, But…

### ISSUE THREAD

**Issue by Bronnel721** [cyrealtype/Vidaloka#1]
This font is great but very limited. Add more glyphs to this font. Also I want this font to be a variable font. And in that variable font I want there to have three axis in it. Witch are the weight axis, (thin - black) the width axis, (ultra compressed - ultra wide) & the optical size axis. (4px - 144px)

**Comment by alexeiva** [comment]
Thank you for your request and compliment. There aren't any plans to extend this family yet.

**Comment by Bronnel721** [comment]
Why not?

**Comment by davelab6** [comment]
You'll need to pay for the work to happen.
